### ISSUE TITLE
No banner display after upgrade to TYPO3 9 LTS

### ISSUE THREAD

**Issue by webian** [derhansen/sf_banners#214]
Hello,
I upgraded this installation from 8 LTS to 9 LTS and the banners are no more displayed.
I'm trying to figure out what's wrong debugging st_banners and core code. 
There seems to be something about the query parameter `type=9001` that it's removed here:
https://github.com/TYPO3/TYPO3.CMS/blob/8cb2b2437f9dea277a1d2fb2463bb025754e03bb/typo3/sysext/core/Classes/Routing/PageRouter.php#L336
If I force `$parameters['type'] = '9001'`, hacking the core code, then the banner displays at least using a tt_content with the sf_banners plugin.

Any idea please?

**Comment by derhansen** [comment]
You need to add a route enhancer for the pageType as shown below

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      banners.html: 9001
```
