### ISSUE TITLE
The page is not configured!

### ISSUE THREAD

**Issue by der-phillip** [derhansen/sf_banners#234]
Hello, I can not get the banners to run. None are displayed to me and the link does not work either.

> The page is not configured! [type=9001][]. This means that there is no TypoScript object of type PAGE with typeNum=9001 configured.

- TS is included
- routeEnhancers are created as follows. If I take the from the tutorial, it also does not work.
```
routeEnhancers
  Suffix:
    type: PageType
    default: /
    index: ''
    map:
      .json: 10
      rss.feed: 200
      sitemap.xml: 1533906435
      ajax: 989862
      banners.html: 9001
      bannerclick.html: 9002
```

TYPO3 11.5.15

Do you have an idea?
